spring:
    application:
        name: spring-ai-mcp-shoping-cart

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: password

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false # ❗ MUST be false

    ai:
        mcp:
            server:
                name: shopping-cart-mcp-server
                version: 1.0.0
                type: SYNC
                stdio: true
    main:
        web-application-type: none
        banner-mode: off

logging:
    level:
        root: OFF # ❗ disables all logs to console
